name: firebase_remote_config_generator
description: Generate Dart code from your Firebase Remote Config.
version: 0.0.1
repository: https://github.com/mikeborodin/firebase_remote_config_generator

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  args: ^2.6.0
  
dev_dependencies:
  test: ^1.25.14
  lints: ^5.1.1
  mocktail: ^1.0.4

executables:
  generate: firebase_remote_config_generator
