name: firebase_remote_config_generator
description: Generate Dart code for Firebase Remote Config.
version: 0.0.1
homepage: https://github.com/mikeborodin/firebase_remote_config_generator

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  googleapis: ^8.1.0
  googleapis_auth: ^1.3.1

dev_dependencies:
  test: ^1.17.1
  lints: ^2.0.0

executables:
  frc_generator: firebase_remote_config_generator
